# Generated by Django 4.1.5 on 2023-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_clothes_options_alter_clothes_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wears')),
            ],
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='image',
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ManyToManyField(to='store.image'),
        ),
    ]
